2019-09-12 21:52:35,636 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,637 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,638 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,639 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,640 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,641 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,642 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,643 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,645 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,646 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,647 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,649 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,650 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,651 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,652 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,653 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,654 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,655 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,655 - crawling.log - INFO - to request target urls
2019-09-12 21:52:35,656 - crawling.log - INFO - to request target urls
2019-09-12 21:52:41,221 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:41,222 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:41,223 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:41,225 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:41,227 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:41,227 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:41,228 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:42,606 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1446613392.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000E653470>, 'Connection to 1.0.200.47 timed out. (connect timeout=3)'))
2019-09-12 21:52:42,676 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417646258.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016815668>, 'Connection to 1.0.200.47 timed out. (connect timeout=3)'))
2019-09-12 21:52:42,696 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417646258.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000166EAFD0>, 'Connection to 51.79.141.39 timed out. (connect timeout=3)'))
2019-09-12 21:52:42,730 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417646258.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016756E48>, 'Connection to 189.89.246.242 timed out. (connect timeout=3)'))
2019-09-12 21:52:43,505 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417911589.html (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2019-09-12 21:52:44,691 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417911589.html (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-09-12 21:52:46,011 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1438098421.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000E5BB9E8>, 'Connection to 181.191.4.163 timed out. (connect timeout=3)'))
2019-09-12 21:52:47,248 - crawling.log - ERROR - request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /jobl/p22/?q=%E5%BB%BA%E7%AD%91%E8%AE%BE%E8%AE%A1%E5%B8%88 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000000001684DEB8>, 'Connection to 157.245.141.144 timed out. (connect timeout=3)'))
2019-09-12 21:52:47,279 - crawling.log - ERROR - request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /jobl/p59/?q=%E6%9C%88%E5%AB%82 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016846400>, 'Connection to 221.6.138.154 timed out. (connect timeout=3)'))
2019-09-12 21:52:47,282 - crawling.log - ERROR - request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /jobl/p22/?q=%E5%BB%BA%E7%AD%91%E8%AE%BE%E8%AE%A1%E5%B8%88 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000000001684DD68>, 'Connection to 112.12.37.196 timed out. (connect timeout=3)'))
2019-09-12 21:52:47,285 - crawling.log - ERROR - request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /jobl/p22/?q=%E5%BB%BA%E7%AD%91%E8%AE%BE%E8%AE%A1%E5%B8%88 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016C98208>, 'Connection to 45.77.187.249 timed out. (connect timeout=3)'))
2019-09-12 21:52:47,321 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1444135371.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CA97B8>, 'Connection to 200.11.14.182 timed out. (connect timeout=3)'))
2019-09-12 21:52:48,872 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1428148741.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CD9B00>, 'Connection to 136.244.70.58 timed out. (connect timeout=3)'))
2019-09-12 21:52:49,066 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417911589.html (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CE1D30>: Failed to establish a new connection: [Errno 10061] [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-09-12 21:52:49,269 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1447901135.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CA3CC0>, 'Connection to 136.244.70.58 timed out. (connect timeout=3)'))
2019-09-12 21:52:50,253 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:50,297 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:50,298 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:50,325 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417911589.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000017043BE0>, 'Connection to 163.204.241.153 timed out. (connect timeout=3)'))
2019-09-12 21:52:50,695 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417911589.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000017043550>, 'Connection to 189.89.246.242 timed out. (connect timeout=3)'))
2019-09-12 21:52:51,464 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1433674930.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000017022278>, 'Connection to 112.12.37.196 timed out. (connect timeout=3)'))
2019-09-12 21:52:51,505 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1433681662.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016469240>, 'Connection to 181.39.86.234 timed out. (connect timeout=3)'))
2019-09-12 21:52:51,749 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1433674930.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CEE470>, 'Connection to 115.124.75.6 timed out. (connect timeout=3)'))
2019-09-12 21:52:52,013 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1438098421.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CCF0B8>, 'Connection to 121.33.220.158 timed out. (connect timeout=3)'))
2019-09-12 21:52:52,018 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1432822875.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CB6B38>, 'Connection to 112.85.164.167 timed out. (connect timeout=3)'))
2019-09-12 21:52:53,513 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1433674930.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000000001704DE80>, 'Connection to 139.99.218.233 timed out. (connect timeout=3)'))
2019-09-12 21:52:54,024 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Read timed out.
2019-09-12 21:52:54,875 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1428148741.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016FEB6A0>, 'Connection to 181.39.86.234 timed out. (connect timeout=3)'))
2019-09-12 21:52:56,269 - crawling.log - ERROR - request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /jobl/p69/?q=%E6%B8%B8%E6%88%8F%E5%8E%9F%E7%94%BB (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000017027668>, 'Connection to 51.79.31.27 timed out. (connect timeout=3)'))
2019-09-12 21:52:56,403 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1444197410.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016FA6E10>, 'Connection to 1.198.73.142 timed out. (connect timeout=3)'))
2019-09-12 21:52:56,564 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417646258.html (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016FD0668>: Failed to establish a new connection: [Errno 10061] [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-09-12 21:52:57,762 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417646258.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CA99E8>, 'Connection to 45.32.132.190 timed out. (connect timeout=3)'))
2019-09-12 21:52:57,815 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1433674930.html (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-09-12 21:52:58,022 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1432822875.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CD9F60>, 'Connection to 109.251.185.20 timed out. (connect timeout=3)'))
2019-09-12 21:52:58,035 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1444197410.html (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-09-12 21:52:58,585 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417911589.html (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out')))
2019-09-12 21:52:59,272 - crawling.log - ERROR - request exception occurred
2019-09-12 21:52:59,490 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1445432808.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000000001681C320>, 'Connection to 95.79.57.206 timed out. (connect timeout=3)'))
2019-09-12 21:53:01,215 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1444197410.html (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2019-09-12 21:53:01,369 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1435252910.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000172856D8>, 'Connection to 115.124.75.6 timed out. (connect timeout=3)'))
2019-09-12 21:53:02,530 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1447436924.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CFE470>, 'Connection to 182.52.51.59 timed out. (connect timeout=3)'))
2019-09-12 21:53:03,271 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1446978428.html (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-09-12 21:53:03,510 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1433674930.html (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-09-12 21:53:04,040 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1444197410.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016F93710>, 'Connection to 202.166.205.78 timed out. (connect timeout=3)'))
2019-09-12 21:53:04,275 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417669939.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000000001750F438>, 'Connection to 91.214.179.24 timed out. (connect timeout=3)'))
2019-09-12 21:53:04,662 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1417669939.html (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-09-12 21:53:04,897 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1441870973.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000174FFAC8>, 'Connection to 45.77.187.249 timed out. (connect timeout=3)'))
2019-09-12 21:53:05,299 - crawling.log - ERROR - request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /jobl/p99/?q=%E5%BB%BA%E7%AD%91%E8%AE%BE%E8%AE%A1%E5%B8%88 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000016CA3438>, 'Connection to 181.39.86.234 timed out. (connect timeout=3)'))
2019-09-12 21:53:05,352 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1442786089.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000017043390>, 'Connection to 202.166.205.78 timed out. (connect timeout=3)'))
2019-09-12 21:53:05,574 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1441870973.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000017528E80>, 'Connection to 1.10.188.202 timed out. (connect timeout=3)'))
2019-09-12 21:53:07,303 - crawling.log - ERROR - second request exception occurred:HTTPSConnectionPool(host='www.kanzhun.com', port=443): Max retries exceeded with url: /job/1444197410.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000017528208>, 'Connection to 157.245.141.144 timed out. (connect timeout=3)'))
